//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products1
    {
        public System.Guid Id { get; set; }
        public string Picture { get; set; }
        public string Name { get; set; }
        public string Star { get; set; }
        public string Price { get; set; }
        public string Original_price { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
    }
}
